// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJ73fXkN_88JMZ44lxAiaosto71RGYKU',
    appId: '1:244034904592:web:e8013c1ccd0ff0d6ae6095',
    messagingSenderId: '244034904592',
    projectId: 'zomatofirebase-7464a',
    authDomain: 'zomatofirebase-7464a.firebaseapp.com',
    storageBucket: 'zomatofirebase-7464a.appspot.com',
    measurementId: 'G-5E3Q4N0MW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeE079DgBQUQgmMU458OprAzFA23l498',
    appId: '1:244034904592:android:1e8c3d3e8befd331ae6095',
    messagingSenderId: '244034904592',
    projectId: 'zomatofirebase-7464a',
    storageBucket: 'zomatofirebase-7464a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKnRFWTLUmCmhtXM6bMmUWGu375aJmSQ',
    appId: '1:244034904592:ios:87d9fba3b90e8c25ae6095',
    messagingSenderId: '244034904592',
    projectId: 'zomatofirebase-7464a',
    storageBucket: 'zomatofirebase-7464a.appspot.com',
    iosBundleId: 'com.example.zomato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKnRFWTLUmCmhtXM6bMmUWGu375aJmSQ',
    appId: '1:244034904592:ios:278c7b1f28d260b4ae6095',
    messagingSenderId: '244034904592',
    projectId: 'zomatofirebase-7464a',
    storageBucket: 'zomatofirebase-7464a.appspot.com',
    iosBundleId: 'com.example.zomato.RunnerTests',
  );
}
