// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7yXa7PUbqsiGT6s7u6NTiY11uS9w_rdI',
    appId: '1:339430727145:web:cf6c3d7f735ab47320bf78',
    messagingSenderId: '339430727145',
    projectId: 'auth-3d057',
    authDomain: 'auth-3d057.firebaseapp.com',
    storageBucket: 'auth-3d057.appspot.com',
    measurementId: 'G-1KXK4782KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnPFGjGx3pm3iJlEXJV0aKfCCEJXbh7s',
    appId: '1:339430727145:android:6c04f47427aa197120bf78',
    messagingSenderId: '339430727145',
    projectId: 'auth-3d057',
    storageBucket: 'auth-3d057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRaOlwRQjE-S8RiiXkenelijsPfHyYG1s',
    appId: '1:339430727145:ios:3076fb47726908eb20bf78',
    messagingSenderId: '339430727145',
    projectId: 'auth-3d057',
    storageBucket: 'auth-3d057.appspot.com',
    iosBundleId: 'com.example.zomato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRaOlwRQjE-S8RiiXkenelijsPfHyYG1s',
    appId: '1:339430727145:ios:05342b2b5bb26dfa20bf78',
    messagingSenderId: '339430727145',
    projectId: 'auth-3d057',
    storageBucket: 'auth-3d057.appspot.com',
    iosBundleId: 'com.example.zomato.RunnerTests',
  );
}
